export const HEADER = {
  GET_BINANCE_PRICES: 'GET_BINANCE_PRICES',
  GET_BINANCE_PRICES_SUCCESS: 'GET_BINANCE_PRICES_SUCCESS',
  GET_BINANCE_PRICES_FAIL: 'GET_BINANCE_PRICES_FAIL',

  GET_USDT_PRICE: 'GET_USDT_PRICE',
  GET_USDT_PRICE_SUCCESS: 'GET_USDT_PRICE_SUCCESS',
  GET_USDT_PRICE_FAIL: 'GET_USDT_PRICE_FAIL',

  GET_GLBX_PRICE: 'GET_GLBX_PRICE',
  GET_GLBX_PRICE_SUCCESS: 'GET_GLBX_PRICE_SUCCESS',
  GET_GLBX_PRICE_FAIL: 'GET_GLBX_PRICE_FAIL',

  GET_USER_INFO: 'GET_USER_INFO',
  GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
  GET_USER_INFO_FAIL: 'GET_USER_INFO_FAIL',

  SET_PRICES: 'SET_PRICES',

  SET_HEADER_ALERT: 'SET_HEADER_ALERT',

  SET_AVATAR: 'SET_AVATAR',
  SET_AVATAR_SUCCESS: 'SET_AVATAR_SUCCESS',
  SET_AVATAR_FAIL: 'SET_AVATAR_FAIL',

  REMOVE_AVATAR: 'REMOVE_AVATAR',
  REMOVE_AVATAR_SUCCESS: 'REMOVE_AVATAR_SUCCESS',
  REMOVE_AVATAR_FAIL: 'REMOVE_AVATAR_FAIL',

  PARTIAL_UPDATES_SECURITY_PARAMS: 'PARTIAL_UPDATES_SECURITY_PARAMS',
  PARTIAL_UPDATES_SECURITY_PARAMS_SUCCESS: 'PARTIAL_UPDATES_SECURITY_PARAMS_SUCCESS',
  PARTIAL_UPDATES_SECURITY_PARAMS_FAIL: 'PARTIAL_UPDATES_SECURITY_PARAMS_FAIL',

  LOGOUT: 'LOGOUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAIL: 'LOGOUT_PARAMS_FAIL'
};
