export const DASHBOARD_ACTIVITY = {
  GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
  GET_NOTIFICATIONS_SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
  GET_NOTIFICATIONS_FAIL: 'GET_NOTIFICATIONS_FAIL',
  
  DELETE_NOTIFICATIONS: 'DELETE_NOTIFICATIONS',
  DELETE_NOTIFICATIONS_SUCCESS: 'DELETE_NOTIFICATIONS_SUCCESS',
  DELETE_NOTIFICATIONS_FAIL: 'DELETE_NOTIFICATIONS_FAIL',
};
