export const WALLETS_ACTIVITY = {
  GET_USERS_WALLETS: 'GET_USERS_WALLETS',
  GET_USERS_WALLETS_SUCCESS: 'GET_USERS_WALLETS_SUCCESS',
  GET_USERS_WALLETS_FAIL: 'GET_USERS_WALLETS_FAIL',
  
  SEND_TO_WALLET: 'SEND_TO_WALLET',
  SEND_TO_WALLET_SUCCESS: 'SEND_TO_WALLET_SUCCESS',
  SEND_TO_WALLET_FAIL: 'SEND_TO_WALLET_FAIL',
};
