export const DASHBOARD_ADVERTISING = {
  GET_ADVERTISING: 'GET_ADVERTISING',
  GET_ADVERTISING_SUCCESS: 'GET_ADVERTISING_SUCCESS',
  GET_ADVERTISING_FAIL: 'GET_ADVERTISING_FAIL',

  GET_ADVERTISING_INNER: 'GET_ADVERTISING_INNER',
  GET_ADVERTISING_INNER_SUCCESS: 'GET_ADVERTISING_INNER_SUCCESS',
  GET_ADVERTISING_INNER_FAIL: 'GET_ADVERTISING_INNER_FAIL',


};
