export const TICKET = {
  CREATE_TICKET: 'CREATE_TICKET',
  CREATE_TICKET_SUCCESS: 'CREATE_TICKET_SUCCESS',
  CREATE_TICKET_FAIL: 'CREATE_TICKET_FAIL',

  DELETE_TICKET: 'DELETE_TICKET',
  DELETE_TICKET_SUCCESS: 'DELETE_TICKET_SUCCESS',
  DELETE_TICKET_FAIL: 'DELETE_TICKET_FAIL',

  GET_TICKETS: 'GET_TICKETS',
  GET_TICKETS_SUCCESS: 'GET_TICKETS_SUCCESS',
  GET_TICKETS_FAIL: 'GET_TICKETS_FAIL',

  GET_SINGLE_TICKET: 'GET_SINGLE_TICKET',
  GET_SINGLE_TICKET_SUCCESS: 'GET_SINGLE_TICKET_SUCCESS',
  GET_SINGLE_TICKET_FAIL: 'GET_SINGLE_TICKET_FAIL',

  CLOSE_SINGLE_TICKET: 'CLOSE_SINGLE_TICKET',
  CLOSE_SINGLE_TICKET_SUCCESS: 'CLOSE_SINGLE_TICKET_SUCCESS',
  CLOSE_SINGLE_TICKET_FAIL: 'CLOSE_SINGLE_TICKET_FAIL',

  OPEN_ARCHIVED_TICKET: 'OPEN_ARCHIVED_TICKET',
  OPEN_ARCHIVED_TICKET_SUCCESS: 'OPEN_ARCHIVED_TICKET_SUCCESS',
  OPEN_ARCHIVED_TICKET_FAIL: 'OPEN_ARCHIVED_TICKET_FAIL',

  SEND_MESSAGE: 'SEND_MESSAGE',
  SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_FAIL: 'SEND_MESSAGE_FAIL',

  GET_MORE_CHAT_MESSAGES: 'GET_MORE_CHAT_MESSAGES',
  GET_MORE_CHAT_MESSAGES_SUCCESS: 'GET_MORE_CHAT_MESSAGES_SUCCESS',
  GET_MORE_CHAT_MESSAGES_FAIL: 'GET_MORE_CHAT_MESSAGES_FAIL',

  ADD_LAST_MESSAGE: 'ADD_LAST_MESSAGE',
  ADD_LAST_MESSAGE_SUCCESS: 'ADD_LAST_MESSAGE_SUCCESS',

  SET_DATA_FROM_WEBSOCKET: 'SET_DATA_FROM_WEBSOCKET',
  SET_DATA_FROM_WEBSOCKET_SUCCESS: 'SET_DATA_FROM_WEBSOCKET_SUCCESS'
};
