export const NEWS = {
  GET_MAIN_THREE: 'GET_MAIN_THREE',
  GET_MAIN_THREE_SUCCESS: 'GET_MAIN_THREE_SUCCESS',
  GET_MAIN_THREE_FAIL: 'GET_MAIN_THREE_FAIL',

  GET_NEWS_TYPE: 'GET_NEWS_TYPE',
  GET_NEWS_TYPE_SUCCESS: 'GET_NEWS_TYPE_SUCCESS',
  GET_NEWS_TYPE_FAIL: 'GET_NEWS_TYPE_FAIL',

  GET_NEWS: 'GET_NEWS',
  GET_NEWS_SUCCESS: 'GET_NEWS_SUCCESS',
  GET_NEWS_FAIL: 'GET_NEWS_FAIL',

  GET_POPULARITY: 'GET_POPULARITY',
  GET_POPULARITY_SUCCESS: 'GET_POPULARITY_SUCCESS',
  GET_POPULARITY_FAIL: 'GET_POPULARITY_FAIL',

  GET_POPULAR: 'GET_POPULAR',
  GET_POPULAR_SUCCESS: 'GET_POPULAR_SUCCESS',
  GET_POPULAR_FAIL: 'GET_POPULAR_FAIL',
};
