export const COIN_PAGE = {
  GET_HEAD_INFO: 'GET_HEAD_INFO',
  GET_HEAD_INFO_SUCCESS: 'GET_HEAD_INFO_SUCCESS',
  GET_HEAD_INFO_FAIL: 'GET_HEAD_INFO_FAIL',

  GET_YOUR_INVESTMENT: 'GET_YOUR_INVESTMENT',
  GET_YOUR_INVESTMENT_SUCCESS: 'GET_YOUR_INVESTMENT_SUCCESS',
  GET_YOUR_INVESTMENT_FAIL: 'GET_YOUR_INVESTMENT_FAIL',

  GET_COIN_NEWS: 'GET_COIN_NEWS',
  GET_COIN_NEWS_SUCCESS: 'GET_COIN_NEWS_SUCCESS',
  GET_COIN_NEWS_FAIL: 'GET_COIN_NEWS_FAIL'
};
