export const REPORTS = {
  GET_REPORTS: 'GET_REPORTS',
  GET_REPORTS_SUCCESS: 'GET_REPORTS_SUCCESS',
  GET_REPORTS_FAIL: 'GET_REPORTS_FAIL',
  
  GET_REPORT_INNER: 'GET_REPORT_INNER',
  GET_REPORT_INNER_SUCCESS: 'GET_REPORT_INNER_SUCCESS',
  GET_REPORT_INNER_FAIL: 'GET_REPORT_INNER_FAIL',
  
  GET_REPORT_INNER_ORDERS: 'GET_REPORT_INNER_ORDERS',
  GET_REPORT_INNER_ORDERS_SUCCESS: 'GET_REPORT_INNER_ORDERS_SUCCESS',
  GET_REPORT_INNER_ORDERS_FAIL: 'GET_REPORT_INNER_ORDERS_FAIL',
};
