export const DASHBOARD_ACTIVITY = {
  GET_WALLETS: 'GET_WALLETS',
  GET_WALLETS_SUCCESS: 'GET_WALLETS_SUCCESS',
  GET_WALLETS_FAIL: 'GET_WALLETS_FAIL',

  CHECK_WALLETS_WITHDRAW: 'CHECK_WALLETS_WITHDRAW',
  CHECK_WALLETS_WITHDRAW_SUCCESS: 'CHECK_WALLETS_WITHDRAW_SUCCESS',
  CHECK_WALLETS_WITHDRAW_FAIL: 'CHECK_WALLETS_WITHDRAW_FAIL',

  DO_WITHDRAW: 'DO_WITHDRAW',
  DO_WITHDRAW_SUCCESS: 'DO_WITHDRAW_SUCCESS',
  DO_WITHDRAW_FAIL: 'DO_WITHDRAW_FAIL',

  SET_ACTIVE_WALLET: 'SET_ACTIVE_WALLET',

  GET_FAQ_WALLETS: 'GET_FAQ_WALLETS',
  GET_FAQ_WALLETS_SUCCESS: 'GET_FAQ_WALLETS_SUCCESS',
  GET_FAQ_WALLETS_FAIL: 'GET_FAQ_WALLETS_FAIL',

  WITHDRAWAL_USDT: 'WITHDRAWAL_USDT',
  WITHDRAWAL_USDT_SUCCESS: 'WITHDRAWAL_USDT_SUCCESS',
  WITHDRAWAL_USDT_FAIL: 'WITHDRAWAL_USDT_FAIL',

  GET_WITHDRAWAL_USDT: 'GET_WITHDRAWAL_USDT',
  GET_WITHDRAWAL_USDT_SUCCESS: 'GET_WITHDRAWAL_USDT_SUCCESS',
  GET_WITHDRAWAL_USDT_FAIL: 'GET_WITHDRAWAL_USDT_FAIL',

  PUT_WITHDRAWAL_USDT: 'PUT_WITHDRAWAL_USDT',
  PUT_WITHDRAWAL_USDT_SUCCESS: 'PUT_WITHDRAWAL_USDT_SUCCESS',
  PUT_WITHDRAWAL_USDT_FAIL: 'PUT_WITHDRAWAL_USDT_FAIL',

  UPDATE_SALES_CONTRACT: 'UPDATE_SALES_CONTRACT',
  UPDATE_SALES_CONTRACT_SUCCESS: 'UPDATE_SALES_CONTRACT_SUCCESS',
  UPDATE_SALES_CONTRACT_FAIL: 'UPDATE_SALES_CONTRACT_FAIL'
};
