export const SETTINGS = {
  SET_AVATAR: 'SET_AVATAR',
  SET_AVATAR_SUCCESS: 'SET_AVATAR_SUCCESS',
  SET_AVATAR_FAIL: 'SET_AVATAR_FAIL',

  REMOVE_AVATAR: 'REMOVE_AVATAR',
  REMOVE_AVATAR_SUCCESS: 'REMOVE_AVATAR_SUCCESS',
  REMOVE_AVATAR_FAIL: 'REMOVE_AVATAR_FAIL',

  SET_FILES_KYC: 'SET_FILES_KYC',
  SET_FILES_KYC_SUCCESS: 'SET_FILES_KYC_SUCCESS',
  SET_FILES_KYC_FAIL: 'SET_FILES_KYC_FAIL',

  REMOVE_FILES_KYC: 'REMOVE_FILES_KYC',
  REMOVE_FILES_KYC_SUCCESS: 'REMOVE_FILES_KYC_SUCCESS',
  REMOVE_FILES_KYC_FAIL: 'REMOVE_FILES_KYC_FAIL',

  GET_FILES_KYC: 'GET_FILES_KYC',
  GET_FILES_KYC_SUCCESS: 'GET_FILES_KYC_SUCCESS',
  GET_FILES_KYC_FAIL: 'GET_FILES_KYC_FAIL',

  GET_QRSECRET: 'GET_QRSECRET',
  GET_QRSECRET_SUCCESS: 'GET_QRSECRET_SUCCESS',
  GET_QRSECRET_FAIL: 'GET_QRSECRET_FAIL',

  CONFIRM_GOOGLECODE: 'CONFIRM_GOOGLECODE',
  CONFIRM_GOOGLECODE_SUCCESS: 'CONFIRM_GOOGLECODE_SUCCESS',
  CONFIRM_GOOGLECODE_FAIL: 'CONFIRM_GOOGLECODE_FAIL',

  SEND_AUTH_EMAIL: 'SEND_AUTH_EMAIL',
  SEND_AUTH_EMAIL_SUCCESS: 'SEND_AUTH_EMAIL_SUCCESS',
  SEND_AUTH_EMAIL_FAIL: 'SEND_AUTH_EMAIL_FAIL',

  TWO_FACTOR_CODE: 'TWO_FACTOR_CODE',
  TWO_FACTOR_CODE_SUCCESS: 'TWO_FACTOR_CODE_SUCCESS',
  TWO_FACTOR_CODE_FAIL: 'TWO_FACTOR_CODE_FAIL',

  CONFIRMATION_ACTION: 'CONFIRMATION_ACTION',
  CONFIRMATION_ACTION_SUCCESS: 'CONFIRMATION_ACTION_SUCCESS',
  CONFIRMATION_ACTION_FAIL: 'CONFIRMATION_ACTION_FAIL',

  RESEND_CODE: 'RESEND_CODE',
  RESEND_CODE_SUCCESS: 'RESEND_CODE_SUCCESS',
  RESEND_CODE_FAIL: 'RESEND_CODE_FAIL',

  GET_REFFERALS: 'GET_REFFERALS',
  GET_REFFERALS_SUCCESS: 'GET_REFFERALS_SUCCESS',
  GET_REFFERALS_FAIL: 'GET_REFFERALS_FAIL',

  GET_REFFERALS_STAKING: 'GET_REFFERALS_STAKING',
  GET_REFFERALS_STAKING_SUCCESS: 'GET_REFFERALS_STAKING_SUCCESS',
  GET_REFFERALS_STAKING_FAIL: 'GET_REFFERALS_STAKING_FAIL',

  GET_REFFERALS_ACCRUALS: 'GET_REFFERALS_ACCRUALS',
  GET_REFFERALS_ACCRUALS_SUCCESS: 'GET_REFFERALS_ACCRUALS_SUCCESS',
  GET_REFFERALS_ACCRUALS_FAIL: 'GET_REFFERALS_ACCRUALS_FAIL',

  SEND_PROMOCODE: 'SEND_PROMOCODE_ACCRUALS',
  SEND_PROMOCODE_SUCCESS: 'SEND_PROMOCODE_SUCCESS',
  SEND_PROMOCODE_FAIL: 'SEND_PROMOCODE_FAIL'
};
