export const AUTH = {
  SIGN_IN: 'SIGN_IN',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',

  SIGN_IN_WITH_EMAIL: 'SIGN_IN_WITH_EMAIL',
  SIGN_IN_WITH_EMAIL_SUCCESS: 'SIGN_IN_WITH_EMAIL_SUCCESS',
  SIGN_IN_WITH_EMAIL_FAIL: 'SIGN_IN_WITH_EMAIL_FAIL',

  PASSWORD_RESET: 'PASSWORD_RESET',
  PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',
  PASSWORD_RESET_FAIL: 'PASSWORD_RESET_FAIL',

  PASSWORD_RECOVERY: ' PASSWORD_RECOVERY',
  PASSWORD_RECOVERY_SUCCESS: ' PASSWORD_RECOVERY_SUCCESS',
  PASSWORD_RECOVERY_FAIL: ' PASSWORD_RECOVERY_FAIL',

  PASSWORD_RECOVERY_TOKEN: ' PASSWORD_RECOVERY_TOKEN',
  PASSWORD_RECOVERY_TOKEN_SUCCESS: ' PASSWORD_RECOVERY_TOKEN_SUCCESS',
  PASSWORD_RECOVERY_TOKEN_FAIL: ' PASSWORD_RECOVERY_TOKEN_FAIL',

  SIGN_UP: 'SIGN_UP',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL',

  VERIFICATION: 'VERIFICATION',
  VERIFICATION_SUCCESS: 'VERIFICATION_SUCCESS',
  VERIFICATION_FAIL: 'VERIFICATION_FAIL',

  USER_ACTIVATION: 'USER_ACTIVATION',
  USER_ACTIVATION_SUCCESS: 'USER_ACTIVATION_SUCCESS',
  USER_ACTIVATION_FAIL: 'USER_ACTIVATION_FAIL'
};
