export const STAKING = {
  GET_STAKING_PAGE_TRANSACTIONS: 'GET_STAKING_PAGE_TRANSACTIONS',
  GET_STAKING_PAGE_TRANSACTIONS_SUCCESS: 'GET_STAKING_PAGE_TRANSACTIONS_SUCCESS',
  GET_STAKING_PAGE_TRANSACTIONS_FAIL: 'GET_STAKING_PAGE_TRANSACTIONS_FAIL',

  GET_STAKING_HISTORY: 'GET_STAKING_HISTORY',
  GET_STAKING_HISTORY_SUCCESS: 'GET_STAKING_HISTORY_SUCCESS',
  GET_STAKING_HISTORY_FAIL: 'GET_STAKING_HISTORY_FAIL',

  GET_FAQ: 'GET_FAQ',
  GET_FAQ_SUCCESS: 'GET_FAQ_SUCCESS',
  GET_FAQ_FAIL: 'GET_FAQ_FAIL',

  GET_STAKING_PERCENTS: 'GET_STAKING_PERCENTS',
  GET_STAKING_PERCENTS_SUCCESS: 'GET_STAKING_PERCENTS_SUCCESS',
  GET_STAKING_PERCENTS_FAIL: 'GET_STAKING_PERCENTS_FAIL',

  GET_STAKING_INFO: 'GET_STAKING_INFO',
  GET_STAKING_INFO_SUCCESS: 'GET_STAKING_INFO_SUCCESS',
  GET_STAKING_INFO_FAIL: 'GET_STAKING_INFO_FAIL',

  GET_STAKING_CHECK: 'GET_STAKING_CHECK',
  GET_STAKING_CHECK_SUCCESS: 'GET_STAKING_CHECK_SUCCESS',
  GET_STAKING_CHECK_FAIL: 'GET_STAKING_CHECK_FAIL',

  GET_STAKING_ADD: 'GET_STAKING_ADD',
  GET_STAKING_ADD_SUCCESS: 'GET_STAKING_ADD_SUCCESS',
  GET_STAKING_ADD_FAIL: 'GET_STAKING_ADD_FAIL',

  GET_STAKING_DESC: 'GET_STAKING_DESC',
  GET_STAKING_DESC_SUCCESS: 'GET_STAKING_DESC_SUCCESS',
  GET_STAKING_DESC_FAIL: 'GET_STAKING_DESC_FAIL',

  SEND_CONTACT_FORM: 'SEND_CONTACT_FORM',
  SEND_CONTACT_FORM_SUCCESS: 'SEND_CONTACT_FORM_SUCCESS',
  SEND_CONTACT_FORM_FAIL: 'SEND_CONTACT_FORM_FAIL',

  GET_ALL_STAKING_DESC: 'GET_ALL_STAKING_DESC',
  GET_ALL_STAKING_DESC_SUCCESS: 'GET_ALL_STAKING_DESC_SUCCESS',
  GET_ALL_STAKING_DESC_FAIL: 'GET_ALL_STAKING_DESC_FAIL',

  DEPOSIT_STAKING: 'DEPOSIT_STAKING',
  DEPOSIT_STAKING_SUCCESS: 'DEPOSIT_STAKING_SUCCESS',
  DEPOSIT_STAKING_FAIL: 'DEPOSIT_STAKING_FAIL',

  DEPOSIT_STAKING_INFO: 'DEPOSIT_STAKING_INFO',
  DEPOSIT_STAKING_INFO_SUCCESS: 'DEPOSIT_STAKING_INFO_SUCCESS',
  DEPOSIT_STAKING_INFO_FAIL: 'DEPOSIT_STAKING_INFO_FAIL',

  GET_TRANSFER: 'GET_TRANSFER',
  GET_TRANSFER_SUCCESS: 'GET_TRANSFER_SUCCESS',
  GET_TRANSFER_FAIL: 'GET_TRANSFER_FAIL',

  GET_USER_STAKINGS: 'GET_USER_STAKINGS',
  GET_USER_STAKINGS_SUCCESS: 'GET_USER_STAKINGS_SUCCESS',
  GET_USER_STAKINGS_FAIL: 'GET_USER_STAKINGS_FAIL',

  STAKING_WITHDRAW: 'STAKING_WITHDRAW',
  STAKING_WITHDRAW_STAKINGS_SUCCESS: 'STAKING_WITHDRAW_SUCCESS',
  STAKING_WITHDRAW_STAKINGS_FAIL: 'STAKING_WITHDRAW_FAIL'
};
