export const WALLET_CHART = {
  WALLET_CHART_INFO: 'WALLET_CHART_INFO',
  WALLET_CHART_INFO_SUCCESS: 'WALLET_CHART_INFO_SUCCESS',
  WALLET_CHART_INFO_FAIL: 'WALLET_CHART_INFO_FAIL',
  
  WALLETS_INFO: 'WALLETS_INFO',
  WALLETS_INFO_SUCCESS: 'WALLETS_INFO_SUCCESS',
  WALLETS_INFO_FAIL: 'WALLETS_INFO_FAIL',
  
  WALLETS_INFO_LOADING: 'WALLETS_INFO_LOADING',
};
