export const LONG_INVESTMENT = {
  GET_DEPOSIT_WALLET: 'GET_DEPOSIT_WALLET',
  GET_DEPOSIT_WALLET_SUCCESS: 'GET_DEPOSIT_WALLET_SUCCESS',
  GET_DEPOSIT_WALLET_FAIL: 'GET_DEPOSIT_WALLET_FAIL',
  
  CHECK_WITHDRAWAL_INFO: 'CHECK_WITHDRAWAL_INFO',
  CHECK_WITHDRAWAL_INFO_SUCCESS: 'CHECK_WITHDRAWAL_INFO_SUCCESS',
  CHECK_WITHDRAWAL_INFO_FAIL: 'CHECK_WITHDRAWAL_INFO_FAIL',
  
  GET_STATISTIC: 'GET_STATISTIC',
  GET_STATISTIC_SUCCESS: 'GET_STATISTIC_SUCCESS',
  GET_STATISTIC_FAIL: 'GET_STATISTIC_FAIL',

  GET_STATISTIC_DASHBOARD: 'GET_STATISTIC_DASHBOARD',
  GET_STATISTIC_DASHBOARD_SUCCESS: 'GET_STATISTIC_DASHBOARD_SUCCESS',
  GET_STATISTIC_DASHBOARD_FAIL: 'GET_STATISTIC_DASHBOARD_FAIL',

  GET_DASHBOARD_BINANCE_INFO: 'GET_DASHBOARD_BINANCE_INFO',
  GET_DASHBOARD_BINANCE_INFO_SUCCESS: 'GET_DASHBOARD_BINANCE_INFO_SUCCESS',
  GET_DASHBOARD_BINANCE_INFO_FAIL: 'GET_DASHBOARD_BINANCE_INFO_FAIL',

  GET_DASHBOARD_BINANCE_BTC: 'GET_DASHBOARD_BINANCE_BTC',
  GET_DASHBOARD_BINANCE_BTC_SUCCESS: 'GET_DASHBOARD_BINANCE_BTC_SUCCESS',
  GET_DASHBOARD_BINANCE_BTC_FAIL: 'GET_DASHBOARD_BINANCE_BTC_FAIL',

  GET_DASHBOARD_BALANCE_INFO: 'GET_DASHBOARD_BALANCE_INFO',
  GET_DASHBOARD_BALANCE_INFO_SUCCESS: 'GET_DASHBOARD_BALANCE_INFO_SUCCESS',
  GET_DASHBOARD_BALANCE_INFO_FAIL: 'GET_DASHBOARD_BALANCE_INFO_FAIL',

  GET_DASHBOARD_INVEST_INFO: 'GET_DASHBOARD_INVEST_INFO',
  GET_DASHBOARD_INVEST_INFO_SUCCESS: 'GET_DASHBOARD_INVEST_INFO_SUCCESS',
  GET_DASHBOARD_INVEST_INFO_FAIL: 'GET_DASHBOARD_INVEST_INFO_FAIL',

  GET_DASHBOARD_BINANCE_PRICE: 'GET_DASHBOARD_BINANCE_PRICE',
  GET_DASHBOARD_BINANCE_PRICE_SUCCESS: 'GET_DASHBOARD_BINANCE_PRICE_SUCCESS',
  GET_DASHBOARD_BINANCE_PRICE_FAIL: 'GET_DASHBOARD_BINANCE_PRICE_FAIL',

  GET_STATISTIC_INNER: 'GET_STATISTIC_INNER',
  GET_STATISTIC_INNER_SUCCESS: 'GET_STATISTIC_INNER_SUCCESS',
  GET_STATISTIC_INNER_FAIL: 'GET_STATISTIC_INNER_FAIL',

  GET_MY_ACTIVITIES_FAIL: 'GET_MY_ACTIVITIES_FAIL',
  GET_MY_ACTIVITIES_SUCCESS: 'GET_MY_ACTIVITIES_SUCCESS',
  GET_MY_ACTIVITIES: 'GET_MY_ACTIVITIES',

  DO_CUSTOM_STATISTIC_LOAD: 'DO_CUSTOM_STATISTIC_LOAD',

  SET_ACTUAL_PRICE: 'SET_ACTUAL_PRICE',

  GET_RECENT_PURCHASES: 'GET_RECENT_PURCHASES',
  GET_RECENT_PURCHASES_SUCCESS: 'GET_RECENT_PURCHASES_SUCCESS',
  GET_RECENT_PURCHASES_FAIL: 'GET_RECENT_PURCHASES_FAIL',

  GET_PORTFOLIO: 'GET_PORTFOLIO',
  GET_PORTFOLIO_SUCCESS: 'GET_PORTFOLIO_SUCCESS',
  GET_PORTFOLIO_FAIL: 'GET_PORTFOLIO_FAIL',

  GET_FORCASTS: 'GET_FORCASTS',
  GET_FORCASTS_SUCCESS: 'GET_FORCASTS_SUCCESS',
  GET_FORCASTS_FAIL: 'GET_FORCASTS_FAIL',

  GET_AVAILABLE_COINS: 'GET_AVAILABLE_COINS',
  GET_AVAILABLE_COINS_SUCCESS: 'GET_AVAILABLE_COINS_SUCCESS',
  GET_AVAILABLE_COINS_FAIL: 'GET_AVAILABLE_COINS_FAIL',

  GET_ALL_COINS: 'GET_ALL_COINS',
  GET_ALL_COINS_SUCCESS: 'GET_ALL_COINS_SUCCESS',
  GET_ALL_COINS_FAIL: 'GET_ALL_COINS_FAIL',

  SEND_AVAILABLE_COINS: 'SEND_AVAILABLE_COINS',
  SEND_AVAILABLE_COINS_SUCCESS: 'SEND_AVAILABLE_COINS_SUCCESS',
  SEND_AVAILABLE_COINS_FAIL: 'SEND_AVAILABLE_COINS_FAIL',

  DELETE_PURCHASES: 'DELETE_PURCHASES',
  DELETE_PURCHASES_SUCCESS: 'DELETE_PURCHASES_SUCCESS',
  DELETE_PURCHASES_FAIL: 'DELETE_PURCHASES_FAIL',

  CURRENCY_RECOMENDATION: 'CURRENCY_RECOMENDATION',
  CURRENCY_RECOMENDATION_SUCCESS: 'CURRENCY_RECOMENDATION_SUCCESS',
  CURRENCY_RECOMENDATION_FAIL: 'CURRENCY_RECOMENDATION_FAIL',

  PROLONG_INVEST_COINS: 'PROLONG_INVEST_COINS',
  PROLONG_INVEST_COINS_SUCCESS: 'PROLONG_INVEST_COINS_SUCCESS',
  PROLONG_INVEST_COINS_FAIL: 'PROLONG_INVEST_COINS_FAIL',

  SLL_COINS: 'SLL_COINS',
  SLL_COINS_SUCCESS: 'SLL_COINS_SUCCESS',
  SLL_COINS_FAIL: 'SLL_COINS_FAIL',

  DELETE_COINS: 'DELETE_COINS',
  DELETE_COINS_SUCCESS: 'DELETE_COINS_SUCCESS',
  DELETE_COINS_FAIL: 'DELETE_COINS_FAIL',

  GET_EXPORT_FORECASTS: 'GET_EXPORT_FORECASTS',
  GET_EXPORT_FORECASTS_SUCCESS: 'GET_EXPORT_FORECASTS_SUCCESS',
  GET_EXPORT_FORECASTS_FAIL: 'GET_EXPORT_FORECASTS_FAIL',

  GET_COIN_COMMISSION: 'GET_COIN_COMMISSION',
  GET_COIN_COMMISSION_SUCCESS: 'GET_COIN_COMMISSION_SUCCESS',
  GET_COIN_COMMISSION_FAIL: 'GET_COIN_COMMISSION_FAIL',

  GET_LABELS_COINS: 'GET_LABELS_COINS',
  GET_LABELS_COINS_SUCCESS: 'GET_LABELS_COINS_SUCCESS',
  GET_LABELS_COINS_FAIL: 'GET_LABELS_COINS_FAIL',

  DEPOSIT_LONG_WALLET: 'DEPOSIT_LONG_WALLET',
  DEPOSIT_LONG_WALLET_SUCCESS: 'DEPOSIT_LONG_WALLET_SUCCESS',
  DEPOSIT_LONG_WALLET_FAIL: 'DEPOSIT_LONG_WALLET_FAIL',

  GET_COIN_MARKETCAP: 'GET_COIN_MARKETCAP',
  GET_COIN_MARKETCAP_SUCCESS: 'GET_COIN_MARKETCAP_SUCCESS',
  GET_COIN_MARKETCAP_FAIL: 'GET_COIN_MARKETCAP_FAIL',

  DEFAULT_BTC: 'DEFAULT_BTC',

  DEFAULT_USDT: 'DEFAULT_USDT'
};
