export const DASHBOARD_STAKING = {
  GET_DASHBOARD_STAKING: 'GET_DASHBOARD_STAKING',
  GET_DASHBOARD_STAKING_SUCCESS: 'GET_DASHBOARD_STAKING_SUCCESS',
  GET_DASHBOARD_STAKING_FAIL: 'GET_DASHBOARD_STAKING_FAIL',
  
  GET_DASHBOARD_STAKING_HISTORY: 'GET_DASHBOARD_STAKING_HISTORY',
  GET_DASHBOARD_STAKING_HISTORY_SUCCESS: 'GET_DASHBOARD_STAKING_HISTORY_SUCCESS',
  GET_DASHBOARD_STAKING_HISTORY_FAIL: 'GET_DASHBOARD_STAKING_HISTORY_FAIL',
};
