export const CHECKS = {

  CHECK_HASH: 'CHECK_HASH',
  CHECK_HASH_SUCCESS: 'CHECK_HASH_SUCCESS',
  CHECK_HASH_FAIL: 'CHECK_HASH_FAIL',

  GET_RISK: 'GET_RISK',
  GET_RISK_SUCCESS: 'GET_RISK_SUCCESS',
  GET_RISK_FAIL: 'GET_RISK_FAIL',

  GET_FREE_CHECKS: 'GET_FREE_CHECKS',
  GET_FREE_CHECKS_SUCCESS: 'GET_FREE_CHECKS_SUCCESS',
  GET_FREE_CHECKS_FAIL: 'GET_FREE_CHECKS_FAIL',

};
