export const DASHBOARD_ACTIVITY = {
  GET_RECENT_TRANSACTIONS: 'GET_RECENT_TRANSACTIONS',
  GET_RECENT_TRANSACTIONS_SUCCESS: 'GET_RECENT_TRANSACTIONS_SUCCESS',
  GET_RECENT_TRANSACTIONS_FAIL: 'GET_RECENT_TRANSACTIONS_FAIL',
  
  GET_WALLET_APPS: 'GET_WALLET_APPS',
  GET_WALLET_APPS_SUCCESS: 'GET_WALLET_APPS_SUCCESS',
  GET_WALLET_APPS_FAIL: 'GET_WALLET_APPS_FAIL',
  
  GET_BINANCE_PRICES: 'GET_BINANCE_PRICES',
  GET_BINANCE_PRICES_SUCCESS: 'GET_BINANCE_PRICES_SUCCESS',
  GET_BINANCE_PRICES_FAIL: 'GET_BINANCE_PRICES_FAIL',

  SET_TRANSACTIONS_LOADING: 'SET_TRANSACTIONS_LOADING'
};
